backend/controllers/UsuariosController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use common\models\Empresa;
use common\models\forms\BusquedaForm;
use common\models\forms\CambiarPasswordForm;
use common\models\Usuarios;
use common\models\GestorUsuarios;
use common\models\GestorRoles;


class UsuariosController extends Controller
{
    
    public function actionIndex()
    {
        return $this->actionListar();
    }
    
    public function actionListar($Cadena = '', $IncluyeBajas = 'N')
    {
        if (!in_array('BuscarUsuarios', Yii::$app->session->get('Permisos')))
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        
        $busqueda = new BusquedaForm();
        if($busqueda->load(Yii::$app->request->post()) && $busqueda->validate())
        {
            $Cadena = $busqueda->Cadena;
            $IncluyeBajas = $busqueda->Check;
        }
        
        $gestor = new GestorUsuarios();
        $usuarios = $gestor->Buscar($Cadena, $IncluyeBajas);
        
        return $this->render('index',[
                    'models' => $usuarios,
                    'busqueda' => $busqueda,
        ]);
    }
    
    public function actionLogin()
    {
        // Si ya estoy logueado redirecciona al home
        if (!Yii::$app->user->isGuest)
            return $this->goHome();

        $this->layout = 'login';
        $usuario = new Usuarios();
        $usuario->setScenario(Usuarios::_LOGIN);
        
        $empresa = new Empresa();
        Yii::$app->session->set('Parametros', ArrayHelper::map($empresa->DameDatos(), 'Parametro', 'Valor'));
        
        if ($usuario->load(Yii::$app->request->post()) && $usuario->validate())
        {
            $login = $usuario->Login($usuario->Password);
          
            if ($login == 'OK')
            {
                Yii::$app->user->login($usuario);
                Yii::$app->session->set('Token', $usuario->Token);
                Yii::$app->session->set('Permisos', $usuario->DamePermisos());
                // El usuario debe modificar el password
                if ($usuario->DebeCambiarPass == 'S')
                {
                    Yii::$app->getSession()->setFlash('info','Debe modificar su contraseña antes de ingresar.');
                    return $this->redirect('/usuarios/cambiar-password');
                }
                else
                    return $this->redirect(Url::to(['/site/index']));
            }
            else
            {
                $usuario->Password = NULL;
                Yii::$app->getSession()->setFlash('danger', $login);
                
                return $this->render('login', [
                            'model' => $usuario,
                ]);
            }
        }
        else
        {
            return $this->render('login', [
                        'model' => $usuario,
            ]);
        }
    }
    
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
        
    public function actionAlta()
    {
        if (!in_array('AltaUsuario', Yii::$app->session->get('Permisos')))
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        
        $usuario = new Usuarios();
        $usuario->setScenario(Usuarios::_ALTA);
        if($usuario->load(Yii::$app->request->post()) && $usuario->validate())
        {      
            Yii::$app->response->format = 'json';
            $gestor = new GestorUsuarios();
            $resultado = $gestor->Alta($usuario);
            if(substr($resultado,0,2) == 'OK')
            {
                return ['error' => null];
            }
            else
            {
                return ['error' => $resultado];
            }
        }
        else
        { 
            $gestorRoles = new GestorRoles();
            $listadoRoles = $gestorRoles->Buscar();
            return $this->renderAjax('datos-usuario',[
                'model' => $usuario,
                'titulo' => 'Alta de usuario',
                'listadoRoles' => $listadoRoles,
            ]);
        }
    }
    
    public function actionModificar($id)
    {
        if (!in_array('ModificarUsuario', Yii::$app->session->get('Permisos')))
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        
        $usuario = new Usuarios();
        $usuario->setScenario(Usuarios::_MODIFICAR);
        if(intval($id))
            $usuario->IdUsuario = $id;
        else
            throw new HttpException('422','El usuario indicado es inválido.');
        
        if($usuario->load(Yii::$app->request->post()) && $usuario->validate())
        {
            Yii::$app->response->format = 'json';
            
            $gestor = new GestorUsuarios();
            $resultado = $gestor->Modificar($usuario);
            if($resultado == 'OK')
            {
                return ['error' => null];
            }
            else
            {
                return ['error' => $resultado];
            }
        }
        else
        {
            $usuario->Dame();
            $gestorRoles = new GestorRoles();
            $roles = $gestorRoles->Buscar();
            return $this->renderAjax('datos-usuario',[
                        'model' => $usuario,
                        'listadoRoles' => $roles,
                        'titulo' => 'Modificar usuario'
            ]);
        }
    }
    
    
    public function actionActivar($id)
    {
        if (!in_array('ActivarUsuario', Yii::$app->session->get('Permisos')))
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        
        $usuario = new Usuarios();
        if(intval($id))
            $usuario->IdUsuario = $id;
        else
            throw new HttpException('422','El usuario indicado es inválido.');
        
        Yii::$app->response->format = 'json';
        $resultado = $usuario->Activar();
        if($resultado == 'OK')
        {
            return ['error' => null];
        }
        else
        {
            return ['error' => $resultado];
        }
    }
    
    public function actionDarBaja($id)
    {
        if (!in_array('DarBajaUsuario', Yii::$app->session->get('Permisos')))
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        
        $usuario = new Usuarios();
        if(intval($id))
            $usuario->IdUsuario = $id;
        else
            throw new HttpException('422','El usuario indicado es inválido.');
        
        Yii::$app->response->format = 'json';
        $resultado = $usuario->DarBaja();
        if($resultado == 'OK')
        {
            return ['error' => null];
        }
        else
        {
            return ['error' => $resultado];
        }
    }
    
    public function actionBorrar($id)
    {
        if (!in_array('BorrarUsuario', Yii::$app->session->get('Permisos')))
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        
        $usuario = new Usuarios();
        if(intval($id))
            $usuario->IdUsuario = $id;
        else
            throw new HttpException('422','El usuario indicado es inválido.');
        
        Yii::$app->response->format = 'json';
        $gestor = new GestorUsuarios();
        $resultado = $gestor->Borrar($usuario);
        if($resultado == 'OK')
        {
            return ['error' => null];
        }
        else
        {
            return ['error' => $resultado];
        }
    }
    
    public function actionCambiarPassword()
    {
        $form = new CambiarPasswordForm();
        $form->setScenario(CambiarPasswordForm::_CAMBIAR);

        $this->layout = 'login';

        if ($form->load(Yii::$app->request->post()) && $form->validate())
        {
            $usuario = Yii::$app->user->identity;

            $mensaje = $usuario->CambiarPassword($usuario->Token,$form->Anterior,$form->Password_repeat);

            if ($mensaje == 'OK')
            {
                Yii::$app->user->logout();
                Yii::$app->session->setFlash('success', 'La contraseña fue modificada.');
                return $this->goHome();
            }
            else
            {
                Yii::$app->session->setFlash('danger', $mensaje);
                return $this->render('password', [
                            'model' => $form,
                ]);
            }
        }
        else
        {
            return $this->render('password', [
                        'model' => $form,
            ]);
        }
    }
    
    public function actionAutocompletar($id = 0, $cadena = '')
    {
        Yii::$app->response->format = 'json';
        
        if($id != 0)
        {
            $usuario = new Usuarios();
            
            $usuario->IdUsuario = $id;
            
            $usuario->Dame();
            
            $out = [
                'id' => $usuario->IdUsuario, 
                'text' => $usuario->NombreCompleto . ' ('.$usuario->Usuario.')'
            ];
        }
        else
        {
            $gestor = new GestorUsuarios();
            
            $usuarios = $gestor->Buscar($cadena, 'N');
            
            $out = array();
            
            foreach($usuarios as $usuario)
            {
                $out[] = [
                    'id' => $usuario['IdUsuario'],

frontend/controllers/UsuariosController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use common\models\Empresa;
use common\models\forms\CambiarPasswordForm;
use common\models\Usuarios;
use common\models\GestorUsuarios;
use common\models\GestorComprobantesPago;
use common\models\UsuariosSucursal;
use common\models\Cajas;

class UsuariosController extends Controller
{
    public function actionLogin()
    {
        // Si ya estoy logueado redirecciona al home
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'login';
        $usuario = new Usuarios();
        $usuario->setScenario(Usuarios::_LOGIN);
        
        $empresa = new Empresa();
        Yii::$app->session->open();
        Yii::$app->session->set('Parametros', ArrayHelper::map($empresa->DameDatos(), 'Parametro', 'Valor'));
        
        if ($usuario->load(Yii::$app->request->post()) && $usuario->validate()) {
            $codigoLlave = Yii::$app->request->post('CodigoLlave');
            $login = $usuario->Login($usuario->Password);
          
            if ($login == 'OK') {
                Yii::$app->user->login($usuario);
                Yii::$app->session->set('Token', $usuario->Token);
                Yii::$app->session->set('Permisos', $usuario->DamePermisos());
                Yii::$app->session->set('codigoLlave', $codigoLlave);

                $caja = new Cajas();
                Yii::$app->session->set('UsoCaja', $caja->DameUsoCajaActual());
                
                // El usuario debe modificar el password
                if ($usuario->DebeCambiarPass == 'S') {
                    Yii::$app->getSession()->setFlash('info', 'Debe modificar su contraseña antes de ingresar.');
                    return $this->redirect('/usuarios/cambiar-password');
                } else {
                    return $this->redirect(Url::to(['/cajas/index']));
                }
            } else {
                $usuario->Password = null;
                Yii::$app->getSession()->setFlash('danger', $login);
                
                return $this->render('login', [
                            'model' => $usuario,
                ]);
            }
        } else {
            return $this->render('login', [
                        'model' => $usuario,
            ]);
        }
    }
    
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
      
    public function actionCambiarPassword()
    {
        $form = new CambiarPasswordForm();
        $form->setScenario(CambiarPasswordForm::_CAMBIAR);

        $this->layout = 'login';

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            $usuario = Yii::$app->user->identity;

            $mensaje = $usuario->CambiarPassword($usuario->Token, $form->Anterior, $form->Password_repeat);

            if ($mensaje == 'OK') {
                Yii::$app->user->logout();
                Yii::$app->session->setFlash('success', 'La contraseña fue modificada.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('danger', $mensaje);
                return $this->render('password', [
                            'model' => $form,
                ]);
            }
        } else {
            return $this->render('password', [
                        'model' => $form,
            ]);
        }
    }
    
    public function actionAutocompletar($id = 0, $cadena = '')
    {
        Yii::$app->response->format = 'json';
        
        if ($id != 0) {
            $usuario = new Usuarios();
            
            $usuario->IdUsuario = $id;
            
            $usuario->Dame();
            
            $out = [
                'id' => $usuario->IdUsuario,
                'text' => $usuario->NombreCompleto . ' ('.$usuario->Usuario.')'
            ];
        } else {
            $gestor = new GestorUsuarios();
            
            $usuarios = $gestor->Buscar($cadena, 'N');
            
            $out = array();
            
            foreach ($usuarios as $usuario) {
                $out[] = [
                    'id' => $usuario['IdUsuario'],
                    'text' => $usuario['NombreCompleto']. ' ('.$usuario['Usuario'].')'
                ];
            }
        }
        return $out;
    }
    
    public function actionDameUsuario($id)
    {
        Yii::$app->response->format = 'json';
        
        $usuario = new Usuarios();
        
        $usuario->IdUsuario = $id;
        
        $usuario->Dame();
        
        return $usuario;
    }
    
    public function actionDamePagos($id)
    {
        Yii::$app->response->format = 'json';
        
        $gestor = new GestorComprobantesPago();

        $pagos = $gestor->DamePagosUsuario($id);

         
        return $pagos;
    }
}

backend/views/usuarios/datos-usuario.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Usuarios */
/* @var $form yii\bootstrap\ActiveForm */
$this->title = $titulo;
?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?= $titulo ?></h4>
            
        </div>
        <div id="errores-modal"></div>
        <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'id' => 'datosusuario-form']); ?>
        <div class="modal-body">
            <?= Html::activeHiddenInput($model, 'IdUsuario') ?>
             
            <?= $form->field($model, 'Usuario'); ?>
            
            <?= $form->field($model, 'Password')->passwordInput([''])?>
                        
            <?= $form->field($model, 'Nombres'); ?>
            
            <?= $form->field($model, 'Apellidos'); ?>            
            
            <?= $form->field($model, 'IdRol')->dropDownList(ArrayHelper::map($listadoRoles, 'IdRol', 'Rol'))?>
            
            <div class="clearfix"></div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary', 'name' => 'rol-button']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/usuarios/index.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $busqueda common\models\forms\BusquedaForm */

$this->title = 'Usuarios';
?>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <div id="errores"></div>
                <?php if (in_array('AltaUsuario', Yii::$app->session->get('Permisos'))) : ?>
                <button type="button" class="btn btn-primary pull-right"
                        data-modal="<?= Url::to(['usuarios/alta']) ?>">
                    <i class="fa fa-plus"></i> Nuevo usuario
                </button>
                <?php endif;?>
                <?php $form = ActiveForm::begin(['id' => 'buscarusuarios-form', 'layout' => 'inline']) ?>
                
                <?= $form->field($busqueda, 'Cadena') ?>
                
                <?= $form->field($busqueda, 'Check')->checkbox(['value' => 'S', 'uncheck' => 'N'])->label('Mostrar desactivados') ?>
                
                <?= Html::submitButton('Buscar', ['class' => 'btn btn-default']) ?>
                
                <?php ActiveForm::end()?>
                <br>
                <?php if (count($models) > 0) : ?>
                <table class="table table-hover">
                    <thead>
                        <tr class="tabla-header">
                            <th>Usuario</th>
                            <th>Apellido/s</th>
                            <th>Nombre/s</th>
                            <th>Rol</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($models as $model) : ?>
                        <tr>
                            <td><?= Html::encode($model['Usuario']) ?></td>
                            <td><?= Html::encode($model['Apellidos']) ?></td>
                            <td><?= Html::encode($model['Nombres']) ?></td>
                            <td><?= Html::encode($model['Rol']) ?></td>
                            <td><?php switch ($model['Estado']) {
                                case 'A': echo 'Activo';
                                    break;
                                case 'B': echo 'Baja';
                                    break;
                            }?></td>
                            <td>
                                <div class="btn-group">
                                    <?php if ($model['Estado'] == 'B' || $model['Estado'] == 'S') : ?>
                                        <?php if (in_array('ActivarUsuario', Yii::$app->session->get('Permisos'))) : ?>
                                        <button type="button" class="btn btn-default"
                                                data-ajax="<?= Url::to(['usuarios/activar', 'id' => $model['IdUsuario']]) ?>"
                                                title="Activar">
                                            <i class="fa fa-check-circle" style="color: green"></i>
                                        </button>
                                        <?php endif; ?>
                                    <?php else : ?>
                                        <?php if (in_array('DarBajaUsuario', Yii::$app->session->get('Permisos'))) : ?>
                                        <button type="button" class="btn btn-default"
                                                data-ajax="<?= Url::to(['usuarios/dar-baja', 'id' => $model['IdUsuario']]) ?>"
                                                title="Dar baja">
                                            <i class="fa fa-minus-circle" style="color: red"></i>
                                        </button>
                                        <?php endif;?>
                                    <?php endif; ?>
                                    <?php if (in_array('ModificarUsuario', Yii::$app->session->get('Permisos'))) : ?>
                                    <button type="button" class="btn btn-default"
                                            data-modal="<?= Url::to(['usuarios/modificar','id' => $model['IdUsuario']]) ?>"
                                            title="Modificar">
                                        <i class="fa fa-edit" style="color: dodgerblue"></i>
                                    </button>
                                    <?php endif; ?>
                                    <?php if (in_array('BorrarUsuario', Yii::$app->session->get('Permisos'))) : ?>
                                    <button type="button" class="btn btn-default"
                                            data-ajax="<?= Url::to(['usuarios/borrar','id' => $model['IdUsuario']]) ?>"
                                            data-mensaje="Seguro desea borrar el usuario?">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>
                        
                        
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else: ?>
                <p><strong>No existen usuarios con el criterio de búsqueda indicado.</strong></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

backend/views/usuarios/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model common\models\Usuarios */

$this->title = 'Ingresar';

?>
<h3 class="login-box-msg"><?= Html::encode($this->title) ?></h3>

<div class="login-box-body">

    <?php
        foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
            echo '<div class="alert alert-' . $key . ' alert-dismissable">'
            . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>'
            . $message . '</div>';
        }

        ?>
    <div id="errores"></div>
    <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
    <div>
        <div class="form-group">
            <?= $form->field($model, 'Usuario')->textInput(['autofocus' => true]) ?>
        </div>
        <div class="form-group">
            <?= $form->field($model, 'Password')->passwordInput() ?>
        </div>          
        
    </div>
    <div class="footer">                                                               
        <?= Html::submitButton('Login', ['class' => 'btn bg-olive btn-block', 'name' => 'login-button']) ?>  
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/views/usuarios/password.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model common\models\forms\CambiarPasswordForm */

$this->title = 'Nueva contraseña';
?>

<h3 class="login-box-msg"><?= Html::encode($this->title) ?></h3>
<div class="login-box-body">
    <?php $form = ActiveForm::begin(); ?>
    <div>
        <?php
        foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
            echo '<div class="alert alert-' . $key . ' alert-dismissable">'
            . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>'
            . $message . '</div>';
        }

        ?>
        <?= $form->field($model, 'Anterior')->passwordInput() ?>

        <?= $form->field($model, 'Password')->passwordInput() ?>

        <?= $form->field($model, 'Password_repeat')->passwordInput() ?>
    </div>

    <div class="footer">                                                               
        <?= Html::submitButton('Cambiar contraseña', ['class' => 'btn bg-olive btn-block',]) ?>  

    </div>
    <?php ActiveForm::end(); ?>
</div>