common/models/Proveedores.php
<?php
namespace common\models;

use Yii;
use yii\base\Model;

/**
 * @version 1.0
 * @created 16-Feb-2017 20:36:56
 */
class Proveedores extends Model
{
    public $IdProveedor;
    public $Proveedor;
    public $Cuit;
    public $Estado;
    
    const _ALTA = 'alta';
    const _MODIFICAR = 'modificar';

    public function rules()
    {
        return [
            //Cuit
            ['Cuit', 'string', 'length' => 11],
            //Alta
            ['Proveedor', 'required', 'on' => self::_ALTA],
            //Modificar
            [['IdProveedor', 'Proveedor'], 'required', 'on' => self::_MODIFICAR],
            //Safe
            [['IdProveedor', 'Proveedor', 'Cuit', 'Estado'], 'safe']
        ];
    }
    /**
     * Permite instanciar un Proveedor desde la base de datos.
     * ssp_dame_proveedor
     */
    public function Dame()
    {
        $sql = 'CALL ssp_dame_proveedor( :idProveedor )';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':idProveedor' => $this->IdProveedor,
        ]);
        
        $this->attributes = $query->queryOne();
    }

    /**
     * Permite cambiar el estado de un proveedor a Activo, controlando que el mismo no
     * se encuentre activo ya.
     * Devuelve OK o un mensaje de error en Mensaje.
     * ssp_activar_proveedor
     */
    public function Activar()
    {
        $sql = 'CALL ssp_activar_proveedor( :token, :idProveedor, :IP, :userAgent, :app)';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':token' => Yii::$app->user->identity->Token,
            ':IP' => Yii::$app->request->userIP,
            ':userAgent' => Yii::$app->request->userAgent,
            ':app' => Yii::$app->id,
            ':idProveedor' => $this->IdProveedor
        ]);
        
        return $query->queryScalar();
    }

    /**
     * Permite cambiar el estado de un proveedor a Baja, controlando que el mismo no
     * se encuentre dado de baja ya.
     * Devuelve OK o un mensaje de error en Mensaje.
     * ssp_darbaja_proveedor
     */
    public function DarBaja()
    {
        $sql = 'CALL ssp_darbaja_proveedor( :token, :idProveedor, :IP, :userAgent, :app)';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':token' => Yii::$app->user->identity->Token,
            ':IP' => Yii::$app->request->userIP,
            ':userAgent' => Yii::$app->request->userAgent,
            ':app' => Yii::$app->id,
            ':idProveedor' => $this->IdProveedor
        ]);
        
        return $query->queryScalar();
    }
}

backend/controllers/ProveedoresController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use common\models\forms\BusquedaForm;
use common\models\GestorProveedores;
use common\models\Proveedores;

class ProveedoresController extends Controller
{
    public function actionIndex()
    {
        return $this->actionListar();
    }
    
    public function actionListar($Cadena = '', $IncluyeBajas = 'N')
    {
        if (!in_array('BuscarProveedores', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $busqueda = new BusquedaForm();
        
        if ($busqueda->load(Yii::$app->request->post()) && $busqueda->validate()) {
            $Cadena = $busqueda->Cadena;
            $IncluyeBajas = $busqueda->Check;
        }
        
        $gestor = new GestorProveedores();
        $models = $gestor->Buscar($Cadena, $IncluyeBajas);
        
        return $this->render('index', [
                    'models' => $models,
                    'busqueda' => $busqueda,
        ]);
    }
    
    public function actionAlta()
    {
        if (!in_array('AltaProveedor', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $proveedor = new Proveedores();
        $proveedor->setScenario(Proveedores::_ALTA);
        if ($proveedor->load(Yii::$app->request->post()) && $proveedor->validate()) {
            Yii::$app->response->format = 'json';
            
            $gestor = new GestorProveedores();
            $resultado = $gestor->Alta($proveedor);
            if (substr($resultado, 0, 2) == 'OK') {
                return ['error' => null];
            } else {
                return ['error' => $resultado];
            }
        } else {
            return $this->renderAjax('datos-proveedor', [
                        'model' => $proveedor,
                        'titulo' => 'Alta de proveedor'
            ]);
        }
    }
    
    public function actionModificar($id)
    {
        if (!in_array('ModificarProveedor', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $proveedor = new Proveedores();
        $proveedor->setScenario(Proveedores::_MODIFICAR);
        if (intval($id)) {
            $proveedor->IdProveedor = $id;
        } else {
            throw new HttpException('422', 'El proveedor indicado es inválido');
        }
        
        if ($proveedor->load(Yii::$app->request->post()) && $proveedor->validate()) {
            Yii::$app->response->format = 'json';
            
            $gestor = new GestorProveedores();
            $resultado = $gestor->Modificar($proveedor);
            if ($resultado == 'OK') {
                return ['error' => null];
            } else {
                return ['error' => $resultado];
            }
        } else {
            $proveedor->Dame();
            return $this->renderAjax('datos-proveedor', [
                        'model' => $proveedor,
                        'titulo' => 'Modificación de proveedor'
            ]);
        }
    }
    
    public function actionActivar($id)
    {
        if (!in_array('ActivarProveedor', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $proveedor = new Proveedores();
        if (intval($id)) {
            $proveedor->IdProveedor = $id;
        } else {
            throw new HttpException('422', 'El proveedor indicado es inválido');
        }
        
        Yii::$app->response->format = 'json';
        
        $resultado = $proveedor->Activar();
        if ($resultado == 'OK') {
            return ['error' => null];
        } else {
            return ['error' => $resultado];
        }
    }
    
    public function actionDarBaja($id)
    {
        if (!in_array('DarBajaProveedor', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $proveedor = new Proveedores();
        if (intval($id)) {
            $proveedor->IdProveedor = $id;
        } else {
            throw new HttpException('422', 'El proveedor indicado es inválido');
        }
        
        Yii::$app->response->format = 'json';
        
        $resultado = $proveedor->DarBaja();
        if ($resultado == 'OK') {
            return ['error' => null];
        } else {
            return ['error' => $resultado];
        }
    }
    
    public function actionBorrar($id)
    {
        if (!in_array('BorrarProveedor', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $proveedor = new Proveedores();
        if (intval($id)) {
            $proveedor->IdProveedor = $id;
        } else {
            throw new HttpException('422', 'El proveedor indicado es inválido');
        }
        
        Yii::$app->response->format = 'json';
        
        $gestor = new GestorProveedores();
        $resultado = $gestor->Borrar($proveedor);
        if ($resultado == 'OK') {
            return ['error' => null];
        } else {
            return ['error' => $resultado];
        }
    }
    
    public function actionAutocompletarProveedores($id = 0, $cadena = '')
    {
        Yii::$app->response->format = 'json';
        
        if ($id != 0) {
            $proveedor = new Proveedores();
            
            $proveedor->IdProveedor = $id;
            
            $proveedor->Dame();
            
            $out = [
                'id' => $proveedor->IdProveedor,
                'text' => $proveedor->Proveedor,
            ];
        } else {
            $gestor = new GestorProveedores();
            
            $proveedores = $gestor->Buscar($cadena);
            
            $out = array();
            
            foreach ($proveedores as $proveedor) {
                $out[] = [
                    'id' => $proveedor['IdProveedor'],
                    'text' => $proveedor['Proveedor']
                ];
            }
        }
        
        return $out;
    }
}

backend/views/proveedores/datos-proveedor.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $model backend\models\Proveedores */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $this yii\web\View */

?>
<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?= $titulo ?></h4>
        </div>

        <?php $form = ActiveForm::begin(['id' => 'datosproveedor-form',]) ?>

        <div class="modal-body">
            <div id="errores-modal"> </div>

            <?= Html::activeHiddenInput($model, 'IdProveedor') ?>
            
            <?= $form->field($model, 'Proveedor') ?>
            
            <?= $form->field($model, 'Cuit') ?>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary',]) ?>  
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/proveedores/index.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

$this->title = 'Proveedores';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <div id="errores"></div>
                <?php if (in_array('AltaProveedor', Yii::$app->session->get('Permisos'))) : ?>
                <button class="btn btn-primary pull-right" type="button"
                        data-modal="<?= Url::to(['proveedores/alta']) ?>">
                    <i class="fa fa-plus"></i> Nuevo proveedor
                </button>
                <?php endif; ?>
                
                <?php $form = ActiveForm::begin(['layout' => 'inline', 'id' => 'busquedaproveedores-form']) ?>
                
                <?= $form->field($busqueda,'Cadena') ?>
                
                <?= $form->field($busqueda,'Check')->checkbox(['value' => 'S', 'uncheck' => 'N'])->label('Mostrar desactivados') ?>
                
                <?= Html::submitButton('Buscar', ['class' => 'btn btn-default', 'name' => 'buscarproveedores-button']) ?> 
                
                <?php ActiveForm::end() ?>
                
                <?php if(count($models) > 0) : ?>
                <table class="table table-hover">
                    <thead>
                        <tr class="tabla-header">
                            <th>Proveedor</th>
                            <th>CUIT</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($models as $model) : ?>
                        <tr>
                            <td><?= Html::encode($model['Proveedor']) ?></td>
                            <td><?= Html::encode($model['Cuit']) ?></td>
                            <td><?php switch($model['Estado']) {
                                case 'A' : echo 'Activo';
                                    break;
                                case 'B' : echo 'Baja';
                                    break;
                            } ?></td>
                            <td>
                                <div class="btn-group">
                                    
                                    <?php if($model['Estado'] == 'A') : ?>
                                        <?php if (in_array('DarBajaProveedor', Yii::$app->session->get('Permisos'))) : ?>
                                        <button class="btn btn-default" type="button"
                                                data-ajax="<?= Url::to(['proveedores/dar-baja', 'id' => $model['IdProveedor']])?>"
                                                title="Desactivar">
                                            <i class="fa fa-minus-circle" style="color: red"></i>
                                        </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if (in_array('ActivarProveedor', Yii::$app->session->get('Permisos'))) : ?>
                                        <button class="btn btn-default" type="button"
                                                data-ajax="<?= Url::to(['proveedores/activar', 'id' => $model['IdProveedor']])?>"
                                                title="Activar">
                                            <i class="fa fa-check-circle" style="color: green"></i>
                                        </button>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if (in_array('ModificarProveedor', Yii::$app->session->get('Permisos'))) : ?>
                                    <button class="btn btn-default" type="button"
                                            data-modal="<?= Url::to(['proveedores/modificar','id' => $model['IdProveedor']]) ?>"
                                            title="Modificar">
                                        <i class="fa fa-edit" style="color: dodgerblue"></i>
                                    </button>
                                    <?php endif; ?>
                                    <?php if (in_array('BorrarProveedor', Yii::$app->session->get('Permisos'))) : ?>
                                    <button class="btn btn-default" type="button"
                                            data-ajax="<?= Url::to(['proveedores/borrar','id' => $model['IdProveedor']]) ?>"
                                            data-mensaje="Desea borrar el proveedor indicado?">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else: ?>
                <p><strong>No existen proveedores con el criterio de búsqueda indicado.</strong></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>