common/models/Roles.php
<?php
namespace common\models;

use Yii;
use yii\base\Model;

/**
 * @version 1.0
 * @created 16-Feb-2017 20:36:56
 */
class Roles extends Model
{
    public $IdRol;
    public $Rol;
    public $Descripcion;
    public $Estado;

    const _ALTA = 'alta';
    const _MODIFICAR = 'modificar';
    const ESTADOS = [
        'A' => 'Activo',
        'B' => 'Baja'
    ];
    
    public function rules()
    {
        return [
            //Alta
            [['Rol', 'Descripcion'], 'required', 'on' => self::_ALTA],
            //Modificar
            [['IdRol', 'Rol', 'Descripcion'], 'required', 'on' => self::_MODIFICAR],
            //Safe
            [['IdRol', 'Rol', 'Descripcion', 'Estado'], 'safe']
        ];
    }
    
    /**
     * Permite instanciar un Rol desde la base de datos.
     * ssp_dame_rol
     */
    public function Dame()
    {
        $sql = 'CALL ssp_dame_rol( :idRol )';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':idRol' => $this->IdRol,
        ]);
        
        $this->attributes = $query->queryOne();
    }

    /**
     * Permite cambiar el estado de un rol a Activo, controlando que el mismo no este
     * activo ya.
     * Devuelve OK o un mensaje de error en Mensaje.
     * ssp_activar_rol
     */
    public function Activar()
    {
        $sql = 'CALL ssp_activar_rol( :token, :idRol, :IP, :userAgent, :app )';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':token' => Yii::$app->user->identity->Token,
            ':IP' => Yii::$app->request->userIP,
            ':userAgent' => Yii::$app->request->userAgent,
            ':app' => Yii::$app->id,
            ':idRol' => $this->IdRol,
        ]);
        
        return $query->queryScalar();
    }

    /**
     * Permite cambiar el estado de un Rol a Baja, controlando que el mismo no este
     * dado de baja ya.
     * Devuelve OK o un mensaje de error en Mensaje.
     * ssp_darbaja_rol
     */
    public function DarBaja()
    {
        $sql = 'CALL ssp_darbaja_rol( :token, :idRol, :IP, :userAgent, :app )';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':token' => Yii::$app->user->identity->Token,
            ':IP' => Yii::$app->request->userIP,
            ':userAgent' => Yii::$app->request->userAgent,
            ':app' => Yii::$app->id,
            ':idRol' => $this->IdRol,
        ]);
        
        return $query->queryScalar();
    }

    /**
     * Permite listar todos los permisos asociados al rol.
     * ssp_listar_permisos_rol
     */
    public function ListarPermisos()
    {
        $sql = 'CALL ssp_listar_permisos_rol( :idRol )';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':idRol' => $this->IdRol,
        ]);
        
        return $query->queryAll();
    }

    /**
     * Permite actualizar los permisos de un rol. Elimina todos los permisos actuales
     * y da de alta los contenidos en pPermisos. Renueva el token de los usuarios que
     * tengan el rol indicado.
     * Devuelve OK o un mensaje de error en Mensaje.
     * ssp_actualizar_permisos_rol
     */
    public function ActualizarPermisos($Permisos)
    {
        $sql = 'CALL ssp_actualizar_permisos_rol( :token, :idRol, :permisos,'
                . ' :IP, :userAgent, :app)';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':token' => Yii::$app->user->identity->Token,
            ':IP' => Yii::$app->request->userIP,
            ':userAgent' => Yii::$app->request->userAgent,
            ':app' => Yii::$app->id,
            ':idRol' => $this->IdRol,
            ':permisos' => $Permisos,
        ]);
        
        return $query->queryScalar();
    }
}

backend/controllers/RolesController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use common\models\forms\BusquedaForm;
use common\models\Roles;
use common\models\GestorRoles;

class RolesController extends Controller
{
    public function actionIndex()
    {
        return $this->actionListar();
    }
    
    public function actionListar($Cadena = '', $IncluyeBajas = 'N')
    {
        if (!in_array('BuscarRoles', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $busqueda = new BusquedaForm();
        if ($busqueda->load(Yii::$app->request->post()) && $busqueda->validate()) {
            $Cadena = $busqueda->Cadena;
            $IncluyeBajas = $busqueda->Check;
        }
        $gestor = new GestorRoles();
        $listadoRoles = $gestor->Buscar($Cadena, $IncluyeBajas);
        
        return $this->render('index', [
                    'models' => $listadoRoles,
                    'busqueda' => $busqueda,
        ]);
    }
    
    public function actionAlta()
    {
        if (!in_array('AltaRol', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $rol = new Roles();
        $rol->setScenario(Roles::_ALTA);
        
        if ($rol->load(Yii::$app->request->post()) && $rol->validate()) {
            Yii::$app->response->format = 'json';
            $gestor = new GestorRoles();
            $resultado = $gestor->Alta($rol);
            if (substr($resultado, 0, 2) == 'OK') {
                return ['error' => null];
            } else {
                return ['error' => $resultado];
            }
        } else {
            return $this->renderAjax('datos-rol', [
                        'model' => $rol,
                        'titulo' => 'Alta de Rol'
            ]);
        }
    }
    
    public function actionModificar($id)
    {
        if (!in_array('ModificarRol', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $rol = new Roles();
        $rol->setScenario(Roles::_MODIFICAR);
        if (intval($id)) {
            $rol->IdRol = $id;
        } else {
            throw new HttpException('422', 'El rol indacdo es inválido');
        }
        
        if ($rol->load(Yii::$app->request->post()) && $rol->validate()) {
            Yii::$app->response->format = 'json';
            $gestor = new GestorRoles();
            $resultado = $gestor->Modificar($rol);
            if ($resultado == 'OK') {
                return ['error' => null];
            } else {
                return ['error' => $resultado];
            }
        } else {
            $rol->Dame();
            return $this->renderAjax('datos-rol', [
                        'model' => $rol,
                        'titulo' => 'Modificar rol',
            ]);
        }
    }
    
    public function actionActivar($id)
    {
        if (!in_array('ActivarRol', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $rol = new Roles();
        if (intval($id)) {
            $rol->IdRol = $id;
        } else {
            throw new HttpException('422', 'El rol indacdo es inválido');
        }
        
        Yii::$app->response->format = 'json';
        $resultado = $rol->Activar();
        if ($resultado == 'OK') {
            return ['error' => null];
        } else {
            return ['error' => $resultado];
        }
    }
    
    public function actionDarBaja($id)
    {
        if (!in_array('DarBajaRol', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $rol = new Roles();
        if (intval($id)) {
            $rol->IdRol = $id;
        } else {
            throw new HttpException('422', 'El rol indacdo es inválido');
        }
        
        Yii::$app->response->format = 'json';
        $resultado = $rol->DarBaja();
        if ($resultado == 'OK') {
            return ['error' => null];
        } else {
            return ['error' => $resultado];
        }
    }
    
    public function actionPermisos($id)
    {
        if (!in_array('BuscarRoles', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $rol = new Roles();
        if (intval($id)) {
            $rol->IdRol = $id;
        } else {
            throw new HttpException('422', 'El rol indacdo es inválido');
        }
        if (Yii::$app->request->isPost) {
            if (!in_array('ActualizarPermisosRol', Yii::$app->session->get('Permisos'))) {
                throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
            }
        
            $permisos = Yii::$app->request->post('Permisos');
            $permisosJson = json_encode(array_keys($permisos));
            
            $resultado = $rol->ActualizarPermisos($permisosJson);
            if ($resultado == 'OK') {
                Yii::$app->session->setFlash('info', 'Permisos modificados con éxito. Reinicie sesión.');
            } else {
                Yii::$app->session->setFlash('danger', $resultado);
            }
        }
        
        $rol->Dame();
        $permisos = $rol->ListarPermisos();

        return $this->render('permisos', [
                    'model' => $rol,
                    'permisos' => $permisos,
        ]);
    }
    
    public function actionBorrar($id)
    {
        if (!in_array('BorrarRol', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $rol = new Roles();
        if (intval($id)) {
            $rol->IdRol = $id;
        } else {
            throw new HttpException('422', 'El rol indacdo es inválido');
        }
        
        Yii::$app->response->format = 'json';
        $gestor = new GestorRoles();
        $resultado = $gestor->Borrar($rol);
        if ($resultado == 'OK') {
            return ['error' => null];
        } else {
            return ['error' => $resultado];
        }
    }
}

backend/views/roles/datos-rol.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model backend\models\Roles */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>
<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?= $titulo ?></h4>
        </div>

        <?php $form = ActiveForm::begin(['id' => 'roles-form',]) ?>

        <div class="modal-body">
            <div id="errores-modal"> </div>

            <?= Html::activeHiddenInput($model, 'IdRol') ?>
            
            <?= $form->field($model, 'Rol') ?>

            <?= $form->field($model, 'Descripcion') ?>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <?= Html::submitButton('Guardar', ['class' => 'btn btn-primary',]) ?>  
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/roles/index.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $busqueda common\models\forms\BusquedaForm */

$this->title = 'Roles y Permisos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <div id="errores"></div>
                <?php if (in_array('AltaRol', Yii::$app->session->get('Permisos'))): ?>
                    <button class="btn btn-primary pull-right" 
                            data-modal="<?= Url::to(['/roles/alta']) ?>">
                        <i class="fa fa-plus"></i> Nuevo Rol
                    </button>
                <?php endif; ?>
                
                <?php $form = ActiveForm::begin(['layout' => 'inline',]); ?>
  
                <?= $form->field($busqueda, 'Cadena') ?> 
                
                <?= $form->field($busqueda, 'Check')->checkbox(['value' => 'S', 'uncheck' => 'N'])->label('Mostrar desactivados') ?> 
                
                <?= Html::submitButton('Buscar', ['class' => 'btn btn-default', 'name' => 'buscarusuario-button']) ?> 

                <?php ActiveForm::end(); ?>
                
                <br>
                
                <?php if (count($models) > 0): ?>
                <table class="table table-hover">
                    <thead>
                        <tr class="tabla-header">
                            <th>Rol</th>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($models as $model): ?>
                        <tr>
                            <td><?= Html::encode($model['Rol']) ?></td>
                            <td><?= Html::encode($model['Descripcion']) ?></td>
                            <td><?php switch ($model['Estado']) {
                                case 'A': echo 'Activo';
                                    break;
                                case 'B': echo 'Baja';
                                    break;
                                default: echo 'ERROR';
                                    break;
                            }?></td>
                            <td>
                                <div class="btn-group">
                                    <?php if ($model['Estado'] == 'A'): ?>
                                    <button class="btn btn-default" 
                                       data-ajax="<?= Url::to(['/roles/dar-baja' , 'id' => Html::encode($model['IdRol'])])?>"
                                       title="Desactivar">
                                        <i class="fa fa-minus-circle" style="color: red"></i>
                                    </button>
                                    <?php else: ?>
                                    <button class="btn btn-default" 
                                       data-ajax="<?= Url::to(['/roles/activar' , 'id' => Html::encode($model['IdRol'])])?>"
                                       title="Activar">
                                        <i class="fa fa-check-circle" style="color: green"></i>
                                    </button>
                                    <?php endif; ?>
                                    <button class="btn btn-default" 
                                       data-modal="<?= Url::to(['/roles/modificar' , 'id' => Html::encode($model['IdRol'])])?>"
                                       title="Modificar">
                                        <i class="fa fa-pencil" style="color: dodgerblue"></i>
                                    </button>
                                    <button class="btn btn-default" 
                                       data-ajax="<?= Url::to(['/roles/borrar' , 'id' => Html::encode($model['IdRol'])])?>"
                                       data-mensaje="Seguro desea eliminar el rol <?= $model['Rol'] ?>?">
                                       <i class="fa fa-trash"></i>
                                    </button>
                                    <a class="btn btn-default" 
                                       href="<?= Url::to(['/roles/permisos' , 'id' => Html::encode($model['IdRol'])])?>"
                                       title="Ver permisos">
                                        <i class="fa fa-key" style="color: goldenrod"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php else: ?>
                <strong>No hay roles que coincidan con el criterio de búsqueda</strong>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

backend/views/roles/permisos.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Permisos de rol: '.$model['Rol'];
$this->params['breadcrumbs'] = [
    [
        'label' => 'Gestión de Usuarios',
        'url'   => ['/usuarios']
    ],
    $this->title,
];
function arbol($permisos, $padre = null)
{
    $edicion = !in_array('ActualizarPermisosRol', Yii::$app->session->get('Permisos'));
    echo '<ul style="list-style-type:none">';
    foreach ($permisos as $permiso) {
        if ($permiso['IdPermisoPadre'] == $padre) {
            echo '<li>';
            if ($permiso['EsHoja'] == 'N') {
                echo '<h4>' . $permiso['Descripcion'] . '</h4>';
                arbol($permisos, $permiso['IdPermiso']);
            } else {
                echo Html::checkbox('Permisos[' . $permiso['IdPermiso'] . ']', $permiso['Estado'] == 'S' ? true : false, ['label' => $permiso['Descripcion'].' ',
                    'class' => 'tree-hoja', 'disabled' => $edicion,]);
                echo '<span class="print-only pull-left"> '. $permiso['Permiso'] .' </span> ';
            }
            echo '</li>';
        }
    }
    echo '</ul>';
}
?>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div id="errores"></div>
            
            <div class="box-body">
               
                <?php $form = ActiveForm::begin(['id' => 'permisos-form']) ?>
                <div class='tree-container'>
                    <?php arbol($permisos) ?>
                </div>   
                
                <?= Html::submitButton('Actualizar permisos', [
                    'class' => 'btn btn-primary pull-right',
                    'disabled' => !in_array('ActualizarPermisosRol', Yii::$app->session->get('Permisos'))]) ?>
                
                <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</div>