common/models/Pedidos.php
<?php
namespace common\models;

use Yii;
use yii\base\Model;

/**
 * @version 1.0
 * @created 16-Feb-2017 20:36:57
 */
class Pedidos extends Model
{
    public $IdPedido;
    public $IdPedidoHijo;
    public $IdCliente;
    public $IdUsuario;
    public $NroPedido;
    public $Importe;
    public $FechaEntrega;
    public $FechaAlta;
    public $Observaciones;
    public $Estado;
    
    //Derivados
    public $IdPedidoPadre;
    public $LineasPedido;
    public $Cliente;
    public $Usuario;
    
    public function attributeLabels()
    {
        return [
            'IdCliente' => 'Cliente',
            'IdUsuario' => 'Usuario',
            'NroPededo' => 'Nro de pedido',
            'FechaEntrega' => 'Fecha de Entrega',
            'FechaAlta' => 'Fecha de Alta',
            'IdPedidoHijo' => 'Pedido original'
        ];
    }
    
    public function rules()
    {
        return [
            //Safe
            [['IdPedido', 'IdPedidoHijo','IdCliente','IdUsuario', 'NroPedido', 'FechaAlta', 'FechaEntrega', 'Estado',
                'LineasPedido', 'Cliente','Usuario', 'Importe','IdPedidoPadre'], 'safe']
        ];
    }
    
    /**
     * Permite instanciar una pedido desde la base de datos
     * ssp_dame_pedido
     */
    public function Dame()
    {
        $sql = 'CALL ssp_dame_pedido( :idpedido )';
        
        $query = Yii::$app->db->createCommand($sql);
        
        $query->bindValues([
            ':idpedido' => $this->IdPedido
        ]);
        
        $this->attributes = $query->queryOne();
    }
}

backend/controllers/PedidosController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use yii\data\Pagination;
use common\models\forms\BusquedaForm;
use common\models\GestorPedidos;
use common\models\Pedidos;
use common\models\Despachos;
use common\models\Usuarios;
use common\models\Clientes;
use common\models\GestorDespachos;
use common\models\GestorClientes;
use common\models\GestorUsuarios;
use yii\helpers\ArrayHelper;

class PedidosController extends Controller
{
    public function actionIndex()
    {
        return $this->actionListar();
    }
    
    public function actionListar($IdUsuario = null, $FechaInicio = null, $FechaFin = null, $Estado = 'A', $IdCliente = null, $IdReparto = null)
    {
        if (!in_array('BuscarPedidos', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $busqueda = new BusquedaForm();
        $paginado = new Pagination();
        $paginado->pageSize = Yii::$app->session->get('Parametros')['CANTFILASPAGINADO'];
        
        if ($busqueda->load(Yii::$app->request->get()) && $busqueda->validate()) {
            $FechaInicio = $busqueda->FechaInicio;
            $FechaFin = $busqueda->FechaFin;
            $Estado = $busqueda->Combo;
            $IdCliente = $busqueda->Combo3;
            $IdUsuario = $busqueda->Combo2;
        } else {
            $busqueda->FechaInicio = $FechaInicio;
            $busqueda->FechaFin = $FechaFin;
            $busqueda->Combo3 = $IdCliente;
            $busqueda->Combo = $Estado ;
            $busqueda->Combo2 = $IdUsuario;
        }
          
        $gestorUsuarios  = new GestorUsuarios();
        $usuarios = ArrayHelper::map($gestorUsuarios->Buscar('', 'N'), 'IdUsuario', 'NombreCompleto');
   
        $gestorClientes = new GestorClientes();
        $clientes = ArrayHelper::map($gestorClientes->Buscar(), 'IdCliente', 'ClienteZona');
        
        $gestorPedidos = new GestorPedidos();
        $pedidos = $gestorPedidos->BuscarAvanzado($IdReparto, $IdCliente, $IdUsuario, $FechaInicio, $FechaFin, $Estado);
        
        $paginado->totalCount = count($pedidos);
        $pedidos = array_slice($pedidos, $paginado->page * $paginado->pageSize, $paginado->pageSize);
        
        return $this->render('index', [
                    'models' => $pedidos,
                    'busqueda' => $busqueda,
                    'paginado' => $paginado,
                    'usuarios' => $usuarios,
                    'clientes' => $clientes,
        ]);
    }
    
    public function actionAlta()
    {
        if (!in_array('AltaVenta', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $pedido = new Pedidos();
        $pedido->FechaEntrega = date('Y-m-d', strtotime('tomorrow'));
        
        $usuario = new Usuarios();
        $usuario->IdUsuario = Yii::$app->user->id;
        $usuario->Dame();
        $pedido->IdUsuario = $usuario->IdUsuario;
        return $this->render('alta', [
                    'model' => $pedido,
                    'usuario' => $usuario,
        ]);
    }
    
    public function actionDetalles($id)
    {
        if (!in_array('BuscarPedidos', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $pedido = new Pedidos();
        if (intval($id)) {
            $pedido->IdPedido = $id;
        } else {
            throw new HttpException('422', 'El pedido indicado es inválido');
        }
        
        $pedido->Dame();
        
        return $this->renderAjax('datos-pedido', [
                'model' => $pedido,
                'titulo' => 'Datos del pedido'
        ]);
    }
    
    public function actionDetallesModificado($id)
    {
        if (!in_array('BuscarPedidos', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
        
        $pedido = new Pedidos();
        if (intval($id)) {
            $pedido->IdPedido = $id;
        } else {
            throw new HttpException('422', 'El pedido indicado es inválido');
        }
        
        $pedido->Dame();
        
        $pedidoHijo = new Pedidos();
        $pedidoHijo->IdPedido = $pedido->IdPedidoHijo;
        $pedidoHijo->Dame();
        
        
        return $this->renderAjax('datos-pedido-modificado', [
                'pedido' => $pedido,
                'pedidoHijo'=> $pedidoHijo,
                'titulo' => 'Datos del pedido modificado'
        ]);
    }
    
    public function actionDespachar($id)
    {
        if (!in_array('AltaDespacho', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
         
        $despacho = new Despachos();
        $pedido = new Pedidos();
        
        if (intval($id)) {
            $pedido->IdPedido = $id;
        } else {
            throw new HttpException('422', 'El pedido indicado es inválida');
        }
        
        $despacho->setScenario(Despachos::_ALTA);
        if ($despacho->load(Yii::$app->request->post()) && $despacho->validate()) {
            Yii::$app->response->format = 'json';
            
            $gestorDespachos = new GestorDespachos();
            $resultado = $gestorDespachos->Alta($despacho);
            if ($resultado == 'OK') {
                return ['error' => null];
            } else {
                return ['error' => $resultado];
            }
        } else {
            $pedido->Dame();

            $despacho->IdPedido = $pedido->IdPedido;
            $despacho->LineasDespacho = $pedido->LineasPedido;

            return $this->renderAjax('/despachos/alta', [
                    'pedido' => $pedido,
                    'model' => $despacho,
                    'titulo' => 'Despachar'
            ]);
        }
    }
    
    public function actionModificar($id = null)
    {
        if (!in_array('AltaPedido', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
          
        if (Yii::$app->request->isPost) {
            Yii::$app->response->format = 'json';
            
            $pedido = new Pedidos();
            $pedido->IdPedido = Yii::$app->request->post('idPedido');
            $pedido->IdCliente = Yii::$app->request->post('idCliente');
            $pedido->IdUsuario = Yii::$app->request->post('idUsuario');
            $pedido->FechaEntrega = Yii::$app->request->post('fechaEntrega');
            
            if ($pedido->IdCliente == 0) {
                $pedido->IdCliente = null;
            }
            if ($pedido->IdUsuario == 0) {
                $pedido->IdUsuario = null;
            }
            
            $pedido->LineasPedido = json_encode(Yii::$app->request->post('lineas'));
            
            $gestor = new GestorPedidos();
            $resultado = $gestor->Modificar($pedido);
            if (substr($resultado, 0, 2) == 'OK') {
                return ['error' => null];
            } else {
                return ['error' => $resultado];
            }
        } else {
            if (!in_array('AltaPedido', Yii::$app->session->get('Permisos'))) {
                return ['error' => 'No tiene permisos para realizar esta acción.'];
            }
         
            $pedido = new Pedidos();
            $pedido->IdPedido = $id;
            $pedido->Dame();
            $pedido->FechaEntrega = date('Y-m-d', strtotime($pedido->FechaEntrega));
            
            $usuario = new Usuarios();
            $usuario->IdUsuario = Yii::$app->user->id;
            $usuario->Dame();
            $pedido->IdUsuario = $usuario->IdUsuario;
            
            return $this->render('alta', [
                        'model' => $pedido,
                        'usuario' => $usuario,
            ]);
        }
    }
    
    public function actionAnular($id = null)
    {
        if (!in_array('AnularPedido', Yii::$app->session->get('Permisos'))) {
            throw new HttpException('403', 'No se tienen los permisos necesarios para ver la página solicitada.');
        }
          
        $pedido = new Pedidos();
        if (intval($id)) {
            $pedido->IdPedido = $id;
        } else {
            throw new HttpException('422', 'El pedido indicado es inválido');
        }
        
        $pedido->Dame();
        
        Yii::$app->response->format = 'json';
        
        $gestor = new GestorPedidos();
        $resultado = $gestor->Anular($pedido);
        if ($resultado == 'OK') {
            return ['error' => null];
        } else {
            return ['error' => $resultado];
        }
    }
    
    public function actionFinalizarPedido()
    {
        Yii::$app->response->format = 'json';
        
        if (!in_array('AltaPedido', Yii::$app->session->get('Permisos'))) {
            return ['error' => 'No tiene permisos para realizar esta acción.'];
        }
        
        if (Yii::$app->request->isPost) {
            $pedido = new Pedidos();
            $pedido->IdCliente = Yii::$app->request->post('idCliente');
            $pedido->IdUsuario = Yii::$app->request->post('idUsuario');
            $pedido->FechaEntrega = Yii::$app->request->post('fechaEntrega');
            
            if ($pedido->IdCliente == 0) {
                $pedido->IdCliente = null;
            }
            if ($pedido->IdUsuario == 0) {
                $pedido->IdUsuario = null;
            }
            
            $pedido->LineasPedido = json_encode(Yii::$app->request->post('lineas'));
            

backend/views/pedidos/datos-pedido-modificado.php
<?php

use yii\helpers\Html;

use yii\helpers\Url;

$lineasPedido = json_decode($pedido['LineasPedido']);
$lineasPedidoHijo = json_decode($pedidoHijo['LineasPedido']);
?>
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?= $titulo ?></h4>
        </div>    
        <div class="modal-body">
            <div id="errores-modal"> </div>
            <?= Html::activeHiddenInput($pedido, 'IdPedido') ?>
            <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">Pedido Nro: <?= Html::encode($pedido['NroPedido']) ?> 
                    <strong class="pull-right"> Pedido original (<?= Html::encode($pedido['Estado'])?>)</strong>
                </div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <div><strong>Usuario:</strong> <?= Html::encode($pedido['Usuario']) ?></div>
                    </div>             
                    <div class="col-md-12">
                        <div><strong>Cliente:</strong> <?= Html::encode($pedido['Cliente']) ?></div>
                    </div>
                    <div class="col-md-12">
                        <div><strong>Fecha alta:</strong><?= Html::encode($pedido['FechaAlta']) ?> </div>
                    </div> 
                </div>
            </div> 
            <?php if (count($lineasPedido) > 0) : ?>
            <table class="table table-hover table-condensed table-bordered ">
                <thead>
                    <tr style="background-color: #C0D8C6"> 
                        <th>Descripción</th>
                        <th>Cantidad</th>  
                        <th>Unidad</th>  
                        <th>Precio</th>  
                        <th>Importe</th>  
                    </tr>
                </thead> 
                <tbody>
                    <?php foreach ($lineasPedido as $linea) : ?>
                    <tr>
                        <td><?= Html::encode($linea->Descripcion) ?></td>
                        <td><?= Html::encode($linea->Unidad) ?></td>
                        <td><?= Html::encode($linea->Cantidad) ?></td> 
                        <td>$ <?= Html::encode($linea->Precio) ?></td> 
                        <td>$ <?= Html::encode($linea->Importe) ?></td>  
                            
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <p><strong>Error al cargar la venta.</strong></p>
            <?php endif; ?>
            </div> 
            <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">Pedido Nro: <?= Html::encode($pedidoHijo['NroPedido']) ?> 
                    <strong class="pull-right"> Pedido nuevo (<?= Html::encode($pedidoHijo['Estado'])?>)</strong> 
                </div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <div><strong>Usuario:</strong> <?= Html::encode($pedidoHijo['Usuario']) ?></div> 
                    </div>             
                    <div class="col-md-12">
                        <div><strong>Cliente:</strong> <?= Html::encode($pedidoHijo['Cliente']) ?></div>
                    </div>
                    <div class="col-md-12">
                        <div><strong>Fecha alta:</strong><?= Html::encode($pedidoHijo['FechaAlta']) ?> </div>
                    </div> 
                </div>
            </div> 
            <?php if (count($lineasPedido) > 0) : ?>
            <table class="table table-hover table-condensed table-bordered ">
                <thead>
                    <tr style="background-color: #C0D8C6"> 
                        <th>Descripción</th>
                        <th>Cantidad</th>  
                        <th>Unidad</th>  
                        <th>Precio</th>  
                        <th>Importe</th>  
                    </tr>
                </thead> 
                <tbody>
                    <?php foreach ($lineasPedidoHijo as $linea) : ?>
                    <tr>
                        <td><?= Html::encode($linea->Descripcion) ?></td>
                        <td><?= Html::encode($linea->Unidad) ?></td>
                        <td><?= Html::encode($linea->Cantidad) ?></td> 
                        <td>$ <?= Html::encode($linea->Precio) ?></td> 
                        <td>$ <?= Html::encode($linea->Importe) ?></td>  
                            
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <?php else: ?>
            <p><strong>Error al cargar la venta.</strong></p>
            <?php endif; ?>
            </div> 
            <div class="clearfix"></div>
        </div> 
        <div class="modal-footer">
            <?php if (in_array('ModificarPedido', Yii::$app->session->get('Permisos')) && $pedido['Estado'] == 'A') : ?>
                <?= Html::a('Modificar', Url::to(['pedidos/modificar','id' => $pedido['IdPedido']]), ['class'=>'btn btn-primary grid-button']) ?>
            <?php endif; ?> 
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>

backend/views/pedidos/datos-pedido.php
<?php

use yii\helpers\Html;

use yii\helpers\Url;

$lineasPedido = json_decode($model['LineasPedido']);
?>
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?= $titulo ?></h4>
        </div>    
        <div class="modal-body">
            <div id="errores-modal"> </div>
            <?= Html::activeHiddenInput($model, 'IdPedido') ?>
            <div class="panel panel-primary">
                <div class="panel-heading">Pedido Nro: <?= Html::encode($model['NroPedido']) ?> </div>
                <div class="panel-body">
                    <div class="col-md-6">
                        <div><strong>Cliente:</strong> <?= Html::encode($model['Cliente']) ?></div>
                    </div>
                    <div class="col-md-6">
                        <div><strong>Fecha de entrega:</strong> <?= Html::encode($model['FechaEntrega']) ?></div> 
                    </div>                        
                    <div class="col-md-6">
                        <div><strong>Usuario:</strong> <?= Html::encode($model['Usuario']) ?></div>
                    </div>
                    <div class="col-md-6">
                        <div><strong>Fecha alta:</strong><?= Html::encode($model['FechaAlta']) ?> </div>
                    </div> 
                </div>
            </div>
            <?php if (count($lineasPedido) > 0) : ?>
            <table class="table table-hover table-condensed table-bordered">
                <thead>
                    <tr style="background-color: #C0D8C6"> 
                        <th>Descripción</th>
                        <th>Cantidad</th>  
                        <th>Unidad</th>  
                        <th>Precio</th>  
                        <th>Importe</th>  
                    </tr>
                </thead> 
                <tbody>
                    <?php foreach ($lineasPedido as $linea) : ?>
                    <tr>
                        <td><?= Html::encode($linea->Descripcion) ?></td>
                        <td><?= Html::encode($linea->Unidad) ?></td>
                        <td><?= Html::encode($linea->Cantidad) ?></td> 
                        <td>$ <?= Html::encode($linea->Precio) ?></td> 
                        <td>$ <?= Html::encode($linea->Importe) ?></td>  
                            
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
                <?php if ($model['IdPedidoPadre' ]!= null): ?>
                    
                    <button type="button" class="btn btn-primary grid-button"
                                                        data-modal="<?= Url::to(['pedidos/detalles-modificado', 'id' => $model['IdPedidoPadre']]) ?>" 
                                                        title="Ver modificaciones">
                        Ver pedido original
                        <i class="fa fa-reply-all"></i>
                    </button> 
                <?php endif; ?>                                 
            <?php else: ?>
            <p><strong>Error al cargar el pedido.</strong></p>
            <?php endif; ?>
        </div>
        <div class="modal-footer">
            <?php if (in_array('ModificarPedido', Yii::$app->session->get('Permisos')) && $model['Estado'] == 'A') : ?>
                <?= Html::a('Modificar', Url::to(['pedidos/modificar','id' => $model['IdPedido']]), ['class'=>'btn btn-primary grid-button']) ?>
            <?php endif; ?> 
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>

backend/views/pedidos/index.php
<?php

use common\assets\PedidosAsset;
use dosamigos\datepicker\DateRangePicker;
use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\LinkPager;

/* @var $this View */
/* @var $form ActiveForm */

$this->title = 'Gestión de pedidos';
$this->params['breadcrumbs'][] = $this->title;

PedidosAsset::register($this);
$this->registerJs('Pedidos.Alta.init()');

$estados = [
    'T' => 'Todos',
    'A' => 'Activo',
    'D' => 'Despachado',
    'B' => 'Baja',
    'M' => 'Modificado',
];
 
$this->title = 'Pedidos';
?>
<div class="row"  id="pedidos">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body"> 
                    <div class="row">
                        <?php if (in_array('AltaPedido', Yii::$app->session->get('Permisos'))) : ?>
                        <a href="<?= Url::to(['pedidos/alta']) ?>">
                            <button class="btn btn-primary pull-right" type="button" >
                            <i class="fa fa-plus"></i> Nuevo pedido
                            </button>
                        </a>
                        <?php endif; ?>
                    </div>
                    <div class="row">
                    <?php $form = ActiveForm::begin(['id' => 'buscarpedidos-form',
                                                    'method' => 'get',
                                                    'layout' => 'inline']) ?>

                    <div class="col-md-4">
                       <?php 
                        $urlClientes = Url::to(['clientes/autocompletar']);
                        echo $form->field($busqueda, 'Combo3')->widget(Select2::className(), [
                                'data' => $clientes,
                                'options' => [
                                  'placeholder' => 'Buscar cliente...',
                                    'v-select2' => 'idCliente',
                                ],
                                'pluginOptions' => [
                                    'width' => '300px',
                                    'allowClear' => true,
                                    
                                ]
                            ]);
                    ?> 
                    <p></p>
                    <?php  
                        echo $form->field($busqueda, 'Combo2')->widget(Select2::className(), [
                                'data' => $usuarios,
                                'options' => [
                                  'placeholder' => 'Buscar vendedor...',
                                    'v-select2' => 'idVendedor',
                                ],
                                'pluginOptions' => [
                                    'width' => '300px',
                                    'allowClear' => true,
                                    
                                ]
                            ]);
                    ?>  
                    </div>
                    <div class="col-md-4">
                        <?= $form->field($busqueda, 'FechaInicio')->widget(DateRangePicker::className(), [
                            'attributeTo' => 'FechaFin',
                            'labelTo' => 'al',
                            'form' => $form,
                            'language' => 'es',
                            'clientOptions' => [
                                'autoclose' => true,
                                'format' => 'dd/mm/yyyy',
                                'endDate' => 'd',
                            ]
                        ])
                        ?>
                        <p></p>
                        <?= $form->field($busqueda, 'Combo')->dropDownList($estados) ?>
                    </div>   
                    <div class="col-md-4">
                    <?= Html::submitButton('Buscar', ['class' => 'btn btn-primary', 'name' => 'buscarpedido-button']) ?> 
                    </div>
                    <?php ActiveForm::end() ?> 
                </div>
                <p></p>
                <div id="errores"></div>
                <?php if (count($models) > 0) : ?>
                <table class="table table-hover">
                    <thead>
                        <tr class="tabla-header">
                            <th>Nº pedido</th> 
                            <th>Usuario</th>
                            <th>Cliente</th>
                            <th>Fecha Engrega</th>
                            <th>Importe</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead> 
                    <tbody>
                        <?php foreach ($models as $model) : ?>
                        <tr v-on:dblclick="clickRow(<?= Html::encode($model['IdPedido']) ?> )">
                            <td><?= Html::encode($model['NroPedido']) ?></td> 
                            <td><?= Html::encode($model['Usuario']) ?></td>
                            <td><?= Html::encode($model['Cliente']) ?></td>
                            <td><?= Html::encode($model['FechaEntrega']) ?></td>
                            <td>$ <?= Html::encode($model['Importe']) ?></td>
                            <td><?= $estados[$model['Estado']] ?></td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default"
                                            data-modal="<?= Url::to(['pedidos/detalles','id' => $model['IdPedido']]) ?>"
                                            title="Detalle del pedido">
                                        <i class="fa fa-search"></i>
                                    </button>
                                    <?php if ($model['Estado'] == 'A'):?>
                                        <?php if (in_array('ModificarPedido', Yii::$app->session->get('Permisos'))) : ?> 
                                        <a  class="btn btn-default" title="Modificar" 
                                            href="<?= Url::to(['pedidos/modificar','id' => $model['IdPedido']]) ?>">
                                            <i class="fa fa-edit"></i>  
                                        </a> 
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    <?php if ($model['Estado'] == 'A'):?>
                                        <?php if (in_array('AltaDespacho', Yii::$app->session->get('Permisos'))) : ?>
                                        <button class="btn btn-default" type="button"
                                                data-modal="<?= Url::to(['pedidos/despachar','id' => $model['IdPedido']]) ?>"
                                                title="Despachar">
                                                <i class="fa fa-truck" ></i> 
                                        </button>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    <?php if ($model['Estado'] != 'B'):?>
                                        <?php if (in_array('AnularPedido', Yii::$app->session->get('Permisos'))) : ?>
                                        <button type="button" class="btn btn-default"
                                                data-ajax="<?= Url::to(['pedidos/anular', 'id' => $model['IdPedido']]) ?>"
                                                data-mensaje="¿Desea anular la pedido?">
                                            <i class="fa fa-ban"></i>
                                        </button>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    <?php if ($model['Estado'] == 'B'):?>
                                        <?php if (in_array('BorrarPedido', Yii::$app->session->get('Permisos'))) : ?>
                                        <button type="button" class="btn btn-default"
                                                data-ajax="<?= Url::to(['pedidos/borrar', 'id' => $model['IdPedido']]) ?>"
                                                data-mensaje="¿Desea borrar el pedido?" >
                                            <i class="fa fa-trash"></i>
                                        </button>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    <?php if ($model['Estado'] == 'M'):?>
                                        <button type="button" class="btn btn-default"
                                                data-modal="<?= Url::to(['pedidos/detalles-modificado', 'id' => $model['IdPedido']]) ?>" 
                                                title="Ver modificaciones">
                                            <i class="fa fa-exchange"></i>
                                        </button> 
                                    <?php endif; ?>
                                    
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="pull-right">
                <?=
                LinkPager::widget([
                    'pagination' => $paginado,
                    'firstPageLabel' => '<<',
                    'lastPageLabel' => '>> ',
                    'nextPageLabel' => '>',
                    'prevPageLabel' => '<'
                ]);
                ?>
                </div>
                <?php else: ?>
                <p><strong>No se registran pedidos en el sistema con los criterios de búsqueda utilizados.</strong></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>